version: "3.7"

networks:
  web:
    external: true
  internal:
    external: false

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:latest'
    container_name: mariadb
    hostname: mariadb
    environment:
      - "MARIADB_DATABASE=${DB_NAME}"
      - "MARIADB_USER=${DB_USER}"
      - "MARIADB_PASSWORD=${DB_PASSWORD}"
      - "MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    networks:
      - internal
    volumes:
    - mariadb-data:/var/lib/mysql
#    healthcheck:
#        test: mysqladmin -p${DB_ROOT_PASSWORD} ping -h localhost
#        timeout: 5s
#        retries: 5
 
  privacyidea:
    build: .
    container_name: mfa
    hostname: mfa
    environment:
      - DB_VENDOR=mariadb
      - DB_HOST=mariadb
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - PI_PEPPER=${PI_PEPPER}
      - PI_PAGE_TITLE=${PI_PAGE_TITLE}
      - PI_EXTERNAL_LINKS=True
      - PI_LOGFILE=${PI_LOGFILE}
      - PI_ADMIN_USER=${PI_ADMIN_USER}
      - PI_ADMIN_PASSWORD=${PI_ADMIN_PASSWORD}
    labels:
      - traefik.http.routers.mfa.rule=Host(`mfa.kion.com.tr`)
      - traefik.http.routers.mfa.tls=true
      - traefik.http.routers.mfa.tls.certresolver=lets-encrypt
      - traefik.port=80
    volumes:
      - ./data:/etc/privacyidea/
    networks:
      - internal
      - web
    depends_on:
      - mariadb
#          condition: service_completed_successfully
    command: wait-for-it mariadb:3306 -- /start.sh

volumes:
  mariadb-data:
